# Generated by Django 5.0.3 on 2024-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('author', 'Autor'), ('translator', 'Translator')], default='author'),
        ),
    ]
